---
title: "Linear Algebra Take Home Exam 1"
author: Aj Averett
format: html
---

# Question 1

```{python}
import numpy as np
import sympy as sp
from sympy import init_printing, Matrix 
init_printing() 

# Question 1

A = Matrix([
    [1,1,0,1,-1,-1,1],
    [0,1,-1,1,-1,0,0],
    [-1,0,1,1,-1,1,-1],
    [0,-1,1,1,-1,-1,-1],
    [1,1,0,0,0,-1,1],
    [1,1,-1,0,-1,-1,-1]])

```
Below is the RREF of Matrix A
```{python}
A.rref()[0]
```

# Question 2

Pivot Columns: 1, 2, 3, 4, 5, 6

# Question 3
Assuming that A is a coefficient matrix, this means that A has 7 vectors with 6 entries per vector. According to Theorem 8, If a set contains more vectors than there are entries in a vector, this means that if A is consistent, it is linearly dependent

# Question 4

```{python}
fifth_column = A[:,4]
other_columns = Matrix(np.delete(A, 4, axis=1))

newA = Matrix(np.append(other_columns, fifth_column, axis = 1))
newArref= newA.rref()[0]
x = newArref[:,-1]
```
The solution set is below

```{python}
x # Solution Set
```
I can show that x is the correct solution set with the code below: In the form $A\vec{x}=\vec{b}$, we know $A$ = A (without the fifth column), $\vec{x}$ is our unique solution set, and $\vec{b}$ is our fifth column of A. Thus $A\vec{x}$ (as shown in the code below) is equal to the fifth column of A.

```{python}
print(other_columns*x) 
```

# Question 5
The columns of $A$ span $\mathbb{R}^6$. According to theorem 4, The columns of A span $\mathbb{R}^6$ if and only if $A$ has a pivot position in each row. Since the RREF of $A$ (as seen in Question 1) has a pivot position in every row, We know that $A$ spans $\mathbb{R}^6$.

# Question 6


```{python}
zeroes = Matrix(np.zeros((6,1)))
A_augmented = Matrix(np.append(A, zeroes, axis = 1))
A_augmented.rref()[0]
```
This shows the following
$$
\begin{cases}
&x_1 = -2x_7\\
&x_2 = x_2\\
&x_3 = x_3\\
&x_4 = -2x_7\\
&x_5 = -2x_7\\
&x_6 = -x_7\\
&x_7 = x_7\\
\end{cases}
\text{ ... thus: }
\vec{x}=
x_2
\begin{bmatrix}
0\\1\\0\\0\\0\\0\\0
\end{bmatrix} +
x_3
\begin{bmatrix}
0\\0\\1\\0\\0\\0\\0
\end{bmatrix}+
x_7
\begin{bmatrix}
-2\\0\\0\\-2\\-2\\-1\\1
\end{bmatrix}
$$

An example of a solution is $\begin{bmatrix}-2\\0\\0\\-2\\-2\\-1\\1\end{bmatrix}$.

# Question 7

```{python}
b = Matrix([1,0,0,0,0,0])
A_augmented2 = Matrix(np.append(A, b, axis = 1))

A_aug2_RREF = A_augmented2.rref()[0]

A_aug2_RREF
```

$$
\vec{x} =x_3 
\begin{bmatrix} 0\\0\\1\\0\\0\\0\\0\end{bmatrix} + x_7 
\begin{bmatrix} -2\\0\\0\\-2\\-2\\1\\1 \end{bmatrix} + 
\begin{bmatrix} 3\\-1\\0\\1\\0\\2\\0\end{bmatrix}
$$

An example of a solution is 'c' below where $x_3$ and $x_7$ are 0.
```{python}
c = Matrix(np.append(A_aug2_RREF[:,-1],0))
print(c)
```
This means $3\vec{a}_1-1\vec{a}_2+0\vec{a}_3+\vec{a}_4+0\vec{a}_5+2\vec{a}_6+0\vec{a}_7 = \vec{b}$
```{python}
add_q7 = Matrix(np.zeros(6))

for i in range(7):
    add_q7 += c[i]*A[:,i]

print(add_q7==b) #Proof
```

# Question 8
Matrix A is a $6\times7$ matrix.

## Part (a)
The domain of T is $\mathbb{R}^6$

## Part (b)
The codomain of T is $\mathbb{R}^6$

## Part (c)
The range of T is $\mathbb{R}^6$ Columns 1,2,3,4,6 and 7 of A have 6 entries in each and are linearly independent meaning that they span $\mathbb{R}^6$ (Theorem 4). While adding the fifth column may make Matrix A linearly dependent, this doesn't change the span.

## Part (d)
If Part (c) is correct, there is no vector in $\mathbb{R}^6$ that is not in the range $T$. 