---
title: "Project 2"
author: "Aj Averett"
date: '2022-05-24'
output:
  rmdformats::readthedown:
    code_folding: hide
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Task 1

The given points are $(t_i, y_i)$ for $i = 1, 2, 3, ... , 44$. The given function models, $f_j(t)$ for $j = 1, 2, 4, 5, 6$, are used to predict a $y$. Additionally, the domain of $f$ is $t >= 0$. To calculate probability and likelihood, the density function, $f(r) = \frac{1}{\sqrt{2\pi\sigma^2}}e^{-\frac{(r-\mu)^2}{2\sigma^2}}$ will be used. For this function, $\mu$ refers to the mean and will be set at 0 and $\sigma$ refers to the standard deviation and will be set to 1.


Finally, for any model $f_j$, we can obtain

* a derived set of residuals or errors, $r_j$,
* a respective probability model, $p_j$,
* a joint probability model, $J_j$,
* a likelihood function, $L_j$, and 
* a log-likelihood function, $\ell_j$.



<br>

## Function One

For points $(t_i, y_i)$ where $i = 1,2,3,...,44$,

* $f_j$ is a model to predict $y_i$ given an $x_i$ where $f_1(t_i) = 100 + a_1t_i$. 

* $r_j$, is a set of residuals calculated for each point where $r_{ji} = y_i-f(x_i)$. This means that the following is true: $r_{1i} = y_i -(100 + a_1t_i) \Leftrightarrow r_{1i} = y_i -100 - a_1t_i \\$

* $p_j$ will be used to denote a probability model of a single residual, $r_{ji}$, where  $p_1(t_i, y_i;a_1) = \frac{1}{\sqrt{2\pi}}e^{-\frac{1}{2}\left(y_i -100 - a_1t_i\right)^2}$. 

* $J_j$ will be used to calculate the joint probability of every residual $r_{ji}$, where $J_1(\overrightarrow{t}, \overrightarrow{y}; a_1) = \prod_{i=1}^{44}\left(\frac{1}{\sqrt{2\pi}}e^{-\frac{1}{2}\left(y_i - 100 - a_1t_i\right)^2}\right)$.

* $L_j$ will be used to calculate the likelihood of the model $f_1$ given the residuals calculated using the points $(t_i,y_i)$ where $L_1(a_1;\overrightarrow{t}, \overrightarrow{y}) = \prod_{i=1}^{44}\left(\frac{1}{\sqrt{2\pi}}e^{-\frac{1}{2}\left(y_i - 100 - a_1t_i\right)^2}\right)$.

* $\ell_j$ will be used to calculate the log-likelihood function from $L$ where 
$\ell_1(a_1;\overrightarrow{t}, \overrightarrow{y})\\$
$$
\begin{align*}
\mathscr{} 
&= \ln(L_1(a_1;\overrightarrow{t}, \overrightarrow{y})) &\text{(definition)}\\
&= \ln\left(\prod_{i=1}^{44}\frac{1}{\sqrt{2\pi}}e^{-\left(y_i - 100 - a_1t_i\right)^2/2}\right) &\text{(substitution)}\\
&= \sum_{i=1}^{44}\ln\left(\frac{1}{\sqrt{2\pi}}e^{-\left(y_i - 100 - a_1t_i\right)^2/2}\right)  &\text{(log product/sum rule)}\\
&= \sum_{i=1}^{44}\left(\ln\left(\frac{1}{\sqrt{2\pi}}\right)+\ln\left(e^{-\left(y_i - 100 - a_1t_i\right)^2/2}\right)\right)&\text{(another product to sum)}\\
&= \sum_{i=1}^{44}\ln\left(\frac{1}{\sqrt{2\pi}}\right)+\sum_{i=1}^{44}\ln\left(e^{-\left(y_i - 100 - a_1t_i\right)^2/2}\right)&\text{(separate the sum)}\\
&= \ln\left(\frac{1}{\sqrt{2\pi}}\right)\sum_{i=1}^{44}1+\sum_{i=1}^{44}\ln\left(e^{-\left(y_i - 100 - a_1t_i\right)^2/2}\right)&\text{(pull out constant)}\\
&= \ln\left(\frac{1}{\sqrt{2\pi}}\right)\sum_{i=1}^{44}1+\sum_{i=1}^{44}-\frac{1}{2}\left(y_i - 100 - a_1t_i\right)^2\ln\left(e\right)&\text{(bring power down)}\\
&= 44\ln\left(\frac{1}{\sqrt{2\pi}}\right)-\frac{1}{2}\sum_{i=1}^{44}\left(y_i - 100 - a_1t_i\right)^2&\text{(simplify)}
\end{align*}
$$
thus, $\ell_1(a_1;\overrightarrow{t}, \overrightarrow{y}) = 44\ln\left(\frac{1}{\sqrt{2\pi}}\right)-\frac{1}{2}\sum_{i=1}^{44}\left(y_i - 100 - a_1t_i\right)^2$


<br>

## Function Two

For points $(t_i, y_i)$ where $i = 1,2,3,...,44$, 

* $f_j$ is a model to predict $y_i$ given an $x_i$ where $f_2(t_i; a_1,a_2) = 100 + a_1t_i + a_2t_i^2$. 

* $r_j$, is a set of residuals calculated for each point where $r_{ji} = y_i-f(x_i)$. This means that the following is true: $r_{2i} = y_i -(100 + a_1t_i + a_2t_i^2) \Leftrightarrow r_{2i} = y_i -100 - a_1t_i - a_2t_i^2 \\$

* $p_j$ will be used to denote a probability model of a single residual, $r_{ji}$, where $p_2(t_i, y_i;a_1,a_2) = \frac{1}{\sqrt{2\pi}}e^{-\frac{1}{2}\left(y_i -100 - a_1t_i - a_2t_i^2\right)^2}$. 

* $J_j$ will be used to calculate the joint probability of every residual $r_{ji}$, where $J_2(\overrightarrow{t}, \overrightarrow{y}; a_1, a_2) = \prod_{i=1}^{44}\left(\frac{1}{\sqrt{2\pi}}e^{-\frac{1}{2}\left(y_i - 100 - a_1t_i\right)^2}\right)$.

* $L_j$ will be used to calculate the likelihood of the model $f_2$ given the residuals calculated using the points $(t_i,y_i)$ where $L_2(a_1, a_2;\overrightarrow{t}, \overrightarrow{y}) = \prod_{i=1}^{44}\left(\frac{1}{\sqrt{2\pi}}e^{-\frac{1}{2}\left(y_i -100 - a_1t_i - a_2t_i^2\right)^2}\right)$.

* $\ell_j$ will be used to calculate the log-likelihood function from $L$ where 
$\ell_2(a_1, a_2;\overrightarrow{t}, \overrightarrow{y})\\$
$$
\begin{align*}
&= \ln(L_2(a_1;\textbf{t},\textbf{y})) &\text{(definition)}\\
&= \ln\left(\prod_{i=1}^{44}\frac{1}{\sqrt{2\pi}}e^{-\left(y_i -100 - a_1t_i - a_2t_i^2\right)^2/2}\right) &\text{(substitution)}\\
&= \sum_{i=1}^{44}\ln\left(\frac{1}{\sqrt{2\pi}}e^{-\left(y_i -100 - a_1t_i - a_2t_i^2\right)^2/2}\right)  &\text{(log product/sum rule)}\\
&= \sum_{i=1}^{44}\left(\ln\left(\frac{1}{\sqrt{2\pi}}\right)+\ln\left(e^{-\left(y_i -100 - a_1t_i - a_2t_i^2\right)^2/2}\right)\right)&\text{(another product to sum)}\\
&= \sum_{i=1}^{44}\ln\left(\frac{1}{\sqrt{2\pi}}\right)+\sum_{i=1}^{44}\ln\left(e^{-\left(y_i -100 - a_1t_i - a_2t_i^2\right)^2/2}\right)&\text{(separate the sum)}\\
&= \ln\left(\frac{1}{\sqrt{2\pi}}\right)\sum_{i=1}^{44}1+\sum_{i=1}^{44}\ln\left(e^{-\left(y_i -100 - a_1t_i - a_2t_i^2\right)^2/2}\right)&\text{(pull out constant)}\\
&= \ln\left(\frac{1}{\sqrt{2\pi}}\right)\sum_{i=1}^{44}1+\sum_{i=1}^{44}-\frac{1}{2}\left(y_i -100 - a_1t_i - a_2t_i^2\right)^2\ln\left(e\right)&\text{(bring power down)}\\
&= 44\ln\left(\frac{1}{\sqrt{2\pi}}\right)-\frac{1}{2}\sum_{i=1}^{44}\left(y_i -100 - a_1t_i - a_2t_i^2\right)^2&\text{(simplify)}
\end{align*}
$$
thus, $\ell_2(a_1,a_2;\overrightarrow{t}, \overrightarrow{y}) = 44\ln\left(\frac{1}{\sqrt{2\pi}}\right)-\frac{1}{2}\sum_{i=1}^{44}\left(y_i -100 - a_1t_i - a_2t_i^2\right)^2$
<br>

## Function Four

For points $(t_i, y_i)$ where $i = 1,2,3,...,44$, 

* $f_j$ is a model to predict $y_i$ given an $x_i$ where $f_4(t; a_1,a_2) = 100 + a_1t + a_2\ln(0.005t+1)$. 

* $r_j$, is a set of residuals calculated for each point where $r_{ji} = y_i-f(x_i)$. This means that the following is true: $r_{4i} = y_i -(100 + a_1t_i + a_2\ln(0.005t_i+1)) \Leftrightarrow r_{4i} = y_i -100 - a_1t_i - a_2\ln(0.005t_i+1)\\$

* $p_j$ will be used to denote a probability model of a single residual, $r_{ji}$, where $p_4(t_i, y_i;a_1,a_2) = \frac{1}{\sqrt{2\pi}}e^{-\frac{1}{2}\left(y_i -100 - a_1t_i - a_2\ln(0.005t_i+1)\right)^2}$. 

* $J_j$ will be used to calculate the joint probability of every residual $r_{ji}$, where $J_4(\overrightarrow{t}, \overrightarrow{y}; a_1, a_2) = \prod_{i=1}^{44}\left(\frac{1}{\sqrt{2\pi}}e^{-\frac{1}{2}\left(y_i -100 - a_1t_i - a_2\ln(0.005t_i+1)\right)^2}\right)$.

* $L_j$ will be used to calculate the likelihood of the model $f_2$ given the residuals calculated using the points $(t_i,y_i)$ where $L_4(a_1, a_2;\overrightarrow{t}, \overrightarrow{y}) = \prod_{i=1}^{44}\left(\frac{1}{\sqrt{2\pi}}e^{-\frac{1}{2}\left(y_i -100 - a_1t_i - a_2\ln(0.005t_i+1)\right)^2}\right)$.

* $\ell_j$ will be used to calculate the log-likelihood function from $L$ where 
$\ell_4(a_1, a_2;\overrightarrow{t}, \overrightarrow{y})\\$

$$
\begin{align*}
&= \ln(L_4(a_1;\textbf{t},\textbf{y})) &\text{(definition)}\\
&= \ln\left(\prod_{i=1}^{44}\frac{1}{\sqrt{2\pi}}e^{-\left(y_i -100 - a_1t_i - a_2\ln(0.005t_i+1)\right)^2/2}\right) &\text{(substitution)}\\
&= \sum_{i=1}^{44}\ln\left(\frac{1}{\sqrt{2\pi}}e^{-\left(y_i -100 - a_1t_i - a_2\ln(0.005t_i+1)\right)^2/2}\right)  &\text{(log product/sum rule)}\\
&= \sum_{i=1}^{44}\left(\ln\left(\frac{1}{\sqrt{2\pi}}\right)+\ln\left(e^{-\left(y_i -100 - a_1t_i - a_2\ln(0.005t_i+1)\right)^2/2}\right)\right)&\text{(another product to sum)}\\
&= \sum_{i=1}^{44}\ln\left(\frac{1}{\sqrt{2\pi}}\right)+\sum_{i=1}^{44}\ln\left(e^{-\left(y_i -100 - a_1t_i - a_2\ln(0.005t_i+1)\right)^2/2}\right)&\text{(separate the sum)}\\
&= \ln\left(\frac{1}{\sqrt{2\pi}}\right)\sum_{i=1}^{44}1+\sum_{i=1}^{44}\ln\left(e^{-\left(y_i -100 - a_1t_i - a_2\ln(0.005t_i+1)\right)^2/2}\right)&\text{(pull out constant)}\\
&= \ln\left(\frac{1}{\sqrt{2\pi}}\right)\sum_{i=1}^{44}1+\sum_{i=1}^{44}-\frac{1}{2}\left(y_i -100 - a_1t_i - a_2\ln(0.005t_i+1)\right)^2\ln\left(e\right)&\text{(bring power down)}\\
&= 44\ln\left(\frac{1}{\sqrt{2\pi}}\right)-\frac{1}{2}\sum_{i=1}^{44}\left(y_i -100 - a_1t_i - a_2\ln(0.005t_i+1)\right)^2&\text{(simplify)}
\end{align*}
$$
thus, $\ell_4(a_1,a_2;\overrightarrow{t}, \overrightarrow{y}) = 44\ln\left(\frac{1}{\sqrt{2\pi}}\right)-\frac{1}{2}\sum_{i=1}^{44}\left(y_i -100 - a_1t_i - a_2\ln(0.005t_i+1)\right)^2$
<br>

## Function Five

For points $(t_i, y_i)$ where $i = 1,2,3,...,44$, 

* $f_j$ is a model to predict $y_i$ given an $x_i$ where $f_5(t; a_1) = 100e^{-0.00005t} + a_1te^{-0.00005t}$. 

* $r_j$, is a set of residuals calculated for each point where $r_{ji} = y_i-f(x_i)$. This means that the following is true: $r_{5i} = y_i -(100e^{-0.00005t_i} + a_1t_ie^{-0.00005t_i}) \Leftrightarrow r_{5i} = y_i -100e^{-0.00005t_i} - a_1t_ie^{-0.00005t_i}\\$


* $p_j$ will be used to denote a probability model of a single residual, $r_{ji}$, where $p_5(t_i, y_i;a_1) = \frac{1}{\sqrt{2\pi}}e^{-\frac{1}{2}\left(y_i -100e^{-0.00005t_i} - a_1t_ie^{-0.00005t_i}\right)^2}$. 

* $J_j$ will be used to calculate the joint probability of every residual $r_{ji}$, where $J_5(\overrightarrow{t}, \overrightarrow{y}; a_1) = \prod_{i=1}^{44}\left(\frac{1}{\sqrt{2\pi}}e^{-\frac{1}{2}\left(y_i -100e^{-0.00005t_i} - a_1t_ie^{-0.00005t_i}\right)^2}\right)$.

* $L_j$ will be used to calculate the likelihood of the model $f_2$ given the residuals calculated using the points $(t_i,y_i)$ where $L_5(a_1;\overrightarrow{t}, \overrightarrow{y}) = \prod_{i=1}^{44}\left(\frac{1}{\sqrt{2\pi}}e^{-\frac{1}{2}\left(y_i -100e^{-0.00005t_i} - a_1t_ie^{-0.00005t_i}\right)^2}\right)$.

* $\ell_j$ will be used to calculate the log-likelihood function from $L$ where 
$\ell_5(a_1;\overrightarrow{t}, \overrightarrow{y})\\$

$$
\begin{align*}
&= \ln(L_5(a_1;\textbf{t},\textbf{y})) &\text{(definition)}\\
&= \ln\left(\prod_{i=1}^{44}\frac{1}{\sqrt{2\pi}}e^{-\left(y_i -100e^{-0.00005t_i} - a_1t_ie^{-0.00005t_i}\right)^2/2}\right) &\text{(substitution)}\\
&= \sum_{i=1}^{44}\ln\left(\frac{1}{\sqrt{2\pi}}e^{-\left(y_i -100e^{-0.00005t_i} - a_1t_ie^{-0.00005t_i}\right)^2/2}\right)  &\text{(log product/sum rule)}\\
&= \sum_{i=1}^{44}\left(\ln\left(\frac{1}{\sqrt{2\pi}}\right)+\ln\left(e^{-\left(y_i -100e^{-0.00005t_i} - a_1t_ie^{-0.00005t_i}\right)^2/2}\right)\right)&\text{(another product to sum)}\\
&= \sum_{i=1}^{44}\ln\left(\frac{1}{\sqrt{2\pi}}\right)+\sum_{i=1}^{44}\ln\left(e^{-\left(y_i -100e^{-0.00005t_i} - a_1t_ie^{-0.00005t_i}\right)^2/2}\right)&\text{(separate the sum)}\\
&= \ln\left(\frac{1}{\sqrt{2\pi}}\right)\sum_{i=1}^{44}1+\sum_{i=1}^{44}\ln\left(e^{-\left(y_i -100e^{-0.00005t_i} - a_1t_ie^{-0.00005t_i}\right)^2/2}\right)&\text{(pull out constant)}\\
&= \ln\left(\frac{1}{\sqrt{2\pi}}\right)\sum_{i=1}^{44}1+\sum_{i=1}^{44}-\frac{1}{2}\left(y_i -100e^{-0.00005t_i} - a_1t_ie^{-0.00005t_i}\right)^2\ln\left(e\right)&\text{(bring power down)}\\
&= 44\ln\left(\frac{1}{\sqrt{2\pi}}\right)-\frac{1}{2}\sum_{i=1}^{44}\left(y_i -100e^{-0.00005t_i} - a_1t_ie^{-0.00005t_i}\right)^2&\text{(simplify)}
\end{align*}
$$
thus, $\ell_5(a_1;\overrightarrow{t}, \overrightarrow{y}) = 44\ln\left(\frac{1}{\sqrt{2\pi}}\right)-\frac{1}{2}\sum_{i=1}^{44}\left(y_i -100e^{-0.00005t_i} - a_1t_ie^{-0.00005t_i}\right)^2$
<br>

## Function Six

For points $(t_i, y_i)$ where $i = 1,2,3,...,44$, 

* $f_j$ is a model to predict $y_i$ given an $x_i$ where $f_6(t; a_1,a_2) = 100 + a_1t + a_2(1-e^{-0.0003t})$. 

* $r_j$, is a set of residuals calculated for each point where $r_{ji} = y_i-f(x_i)$. This means that the following is true: $r_{6i} = y_i -(100 + a_1t_i + a_2(1-e^{-0.0003t_i})) \Leftrightarrow r_{6i} = y_i -100 - a_1t_i - a_2(1-e^{-0.0003t_i})\\$.

* $p_j$ will be used to denote a probability model of a single residual, $r_{ji}$, where $p_6(t_i, y_i;a_1,a_2) = \frac{1}{\sqrt{2\pi}}e^{-\frac{1}{2}\left(y_i -100 - a_1t_i - a_2(1-e^{-0.0003t_i})\right)^2}$. 

* $J_j$ will be used to calculate the joint probability of every residual $r_{ji}$, where $J_6(\overrightarrow{t}, \overrightarrow{y}; a_1, a_2) = \prod_{i=1}^{44}\left(\frac{1}{\sqrt{2\pi}}e^{-\frac{1}{2}\left(y_i -100 - a_1t_i - a_2(1-e^{-0.0003t_i})\right)^2}\right)$.

* $L_j$ will be used to calculate the likelihood of the model $f_6$ given the residuals calculated using the points $(t_i,y_i)$ where $L_6(a_1, a_2;\overrightarrow{t}, \overrightarrow{y}) = \prod_{i=1}^{44}\left(\frac{1}{\sqrt{2\pi}}e^{-\frac{1}{2}\left(y_i -100 - a_1t_i - a_2(1-e^{-0.0003t_i})\right)^2}\right)$.

* $\ell_j$ will be used to calculate the log-likelihood function from $L$ where 
$\ell_6(a_1, a_2;\overrightarrow{t}, \overrightarrow{y})\\$
$$
\begin{align*}
&= \ln(L_6(a_1;\textbf{t},\textbf{y})) &\text{(definition)}\\
&= \ln\left(\prod_{i=1}^{44}\frac{1}{\sqrt{2\pi}}e^{-\left(y_i -100 - a_1t_i - a_2(1-e^{-0.0003t_i})\right)^2/2}\right) &\text{(substitution)}\\
&= \sum_{i=1}^{44}\ln\left(\frac{1}{\sqrt{2\pi}}e^{-\left(y_i -100 - a_1t_i - a_2(1-e^{-0.0003t_i})\right)^2/2}\right)  &\text{(log product/sum rule)}\\
&= \sum_{i=1}^{44}\left(\ln\left(\frac{1}{\sqrt{2\pi}}\right)+\ln\left(e^{-\left(y_i -100 - a_1t_i - a_2(1-e^{-0.0003t_i})\right)^2/2}\right)\right)&\text{(another product to sum)}\\
&= \sum_{i=1}^{44}\ln\left(\frac{1}{\sqrt{2\pi}}\right)+\sum_{i=1}^{44}\ln\left(e^{-\left(y_i -100 - a_1t_i - a_2(1-e^{-0.0003t_i})\right)^2/2}\right)&\text{(separate the sum)}\\
&= \ln\left(\frac{1}{\sqrt{2\pi}}\right)\sum_{i=1}^{44}1+\sum_{i=1}^{44}\ln\left(e^{-\left(y_i -100 - a_1t_i - a_2(1-e^{-0.0003t_i})\right)^2/2}\right)&\text{(pull out constant)}\\
&= \ln\left(\frac{1}{\sqrt{2\pi}}\right)\sum_{i=1}^{44}1+\sum_{i=1}^{44}-\frac{1}{2}\left(y_i -100 - a_1t_i - a_2(1-e^{-0.0003t_i})\right)^2\ln\left(e\right)&\text{(bring power down)}\\
&= 44\ln\left(\frac{1}{\sqrt{2\pi}}\right)-\frac{1}{2}\sum_{i=1}^{44}\left(y_i -100 - a_1t_i - a_2(1-e^{-0.0003t_i})\right)^2&\text{(simplify)}
\end{align*}
$$
thus, $\ell_6(a_1,a_2;\overrightarrow{t}, \overrightarrow{y}) = 44\ln\left(\frac{1}{\sqrt{2\pi}}\right)-\frac{1}{2}\sum_{i=1}^{44}\left(y_i -100 - a_1t_i - a_2(1-e^{-0.0003t_i})\right)^2$
<br>