---
title: "Project 2"
author: "Aj Averett"
date: '2022-05-24'
output:
  rmdformats::readthedown:
    code_folding: hide
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Task 2

The given points are $(t_i, y_i)$ for $i = 1, 2, 3, ... , 44$. The given function models, $f_j(t)$ for $j = 1, 2, 4, 5, 6$, are used to predict a $y$. Additionally, the domain of $f$ is $t >= 0$. To calculate probability and likelihood, the density function, $f(r) = \frac{1}{\sqrt{2\pi\sigma^2}}e^{-\frac{(r-\mu)^2}{2\sigma^2}}$ will be used. For this function, $\mu$ refers to the mean and will be set at 0 and $\sigma$ refers to the standard deviation and will be set to 1.


Finally, for any model $f_j$, we can obtain

* a derived set of residuals or errors, $r_j$,
* a respective probability model, $p_j$,
* a joint probability model, $J_j$,
* a likelihood function, $L_j$, and 
* a log-likelihood function, $\ell_j$.



<br>

## Function One

For points $(t_i, y_i)$ where $i = 1,2,3,...,44$,

* $f_j$ is a model to predict $y_i$ given an $x_i$ where $f_1(t_i) = 100 + a_1t_i$. 

* $r_j$, is a set of residuals calculated for each point where $r_{ji} = y_i-f(x_i)$. This means that the following is true: $r_{1i} = y_i -(100 + a_1t_i) \Leftrightarrow r_{1i} = y_i -100 - a_1t_i \\$

* $p_j$ will be used to denote a probability model of a single residual, $r_{ji}$, where  $p_1(t_i, y_i;a_1) = \frac{1}{\sqrt{2\pi}}e^{-\frac{1}{2}\left(y_i -100 - a_1t_i\right)^2}$. 

* $J_j$ will be used to calculate the joint probability of every residual $r_{ji}$, where $J_1(\overrightarrow{t}, \overrightarrow{y}; a_1) = \prod_{i=1}^{44}\left(\frac{1}{\sqrt{2\pi}}e^{-\frac{1}{2}\left(y_i - 100 - a_1t_i\right)^2}\right)$.

* $L_j$ will be used to calculate the likelihood of the model $f_1$ given the residuals calculated using the points $(t_i,y_i)$ where $L_1(a_1;\overrightarrow{t}, \overrightarrow{y}) = \prod_{i=1}^{44}\left(\frac{1}{\sqrt{2\pi}}e^{-\frac{1}{2}\left(y_i - 100 - a_1t_i\right)^2}\right)$.

* $\ell_j$ will be used to calculate the log-likelihood function from $L$ where 
$\ell_1(a_1;\overrightarrow{t}, \overrightarrow{y})\\$
$$
\begin{align*}
\mathscr{} 
&= \ln(L_1(a_1;\overrightarrow{t}, \overrightarrow{y})) &\text{(definition)}\\
&= \ln\left(\prod_{i=1}^{44}\frac{1}{\sqrt{2\pi}}e^{-\left(y_i - 100 - a_1t_i\right)^2/2}\right) &\text{(substitution)}\\
&= \sum_{i=1}^{44}\ln\left(\frac{1}{\sqrt{2\pi}}e^{-\left(y_i - 100 - a_1t_i\right)^2/2}\right)  &\text{(log product/sum rule)}\\
&= \sum_{i=1}^{44}\left(\ln\left(\frac{1}{\sqrt{2\pi}}\right)+\ln\left(e^{-\left(y_i - 100 - a_1t_i\right)^2/2}\right)\right)&\text{(another product to sum)}\\
&= \sum_{i=1}^{44}\ln\left(\frac{1}{\sqrt{2\pi}}\right)+\sum_{i=1}^{44}\ln\left(e^{-\left(y_i - 100 - a_1t_i\right)^2/2}\right)&\text{(separate the sum)}\\
&= \ln\left(\frac{1}{\sqrt{2\pi}}\right)\sum_{i=1}^{44}1+\sum_{i=1}^{44}\ln\left(e^{-\left(y_i - 100 - a_1t_i\right)^2/2}\right)&\text{(pull out constant)}\\
&= \ln\left(\frac{1}{\sqrt{2\pi}}\right)\sum_{i=1}^{44}1+\sum_{i=1}^{44}-\frac{1}{2}\left(y_i - 100 - a_1t_i\right)^2\ln\left(e\right)&\text{(bring power down)}\\
&= 44\ln\left(\frac{1}{\sqrt{2\pi}}\right)-\frac{1}{2}\sum_{i=1}^{44}\left(y_i - 100 - a_1t_i\right)^2&\text{(simplify)}
\end{align*}
$$
thus, $\ell_1(a_1;\overrightarrow{t}, \overrightarrow{y}) = 44\ln\left(\frac{1}{\sqrt{2\pi}}\right)-\frac{1}{2}\sum_{i=1}^{44}\left(y_i - 100 - a_1t_i\right)^2$


<br>

### Finding the derivatives

Next is to calculate the derivative of $\ell_1(a_1;\overrightarrow{t}, \overrightarrow{y})$.

$\frac{d}{da_1}\ell_1(a_1;\overrightarrow{t}, \overrightarrow{y})=$

$$
\begin{align*}
\mathscr{} 
&= \frac{d}{da_1} \left(\ 44\ln\left(\frac{1}{\sqrt{2\pi}}\right)-\frac{1}{2}\sum_{i=1}^{44}\left(y_i - 100 - a_1t_i\right)^2 \right) &\text{(definition)}\\
&= \frac{d}{da_1} \left(\ 44\ln\left(\frac{1}{\sqrt{2\pi}}\right)\right)-\frac{d}{da_1} \left(\frac{1}{2}\sum_{i=1}^{44}\left(y_i - 100 - a_1t_i\right)^2 \right) &\text{(sum rule)}\\
&= -\frac{d}{da_1} \left(\frac{1}{2}\sum_{i=1}^{44}\left(y_i - 100 - a_1t_i\right)^2 \right) &\text{(constant rule)}\\
&= -\frac{1}{2}\frac{d}{da_1} \left(\sum_{i=1}^{44}\left(y_i - 100 - a_1t_i\right)^2 \right) &\text{(CM rule)}\\
&= -\frac{1}{2} \left(\sum_{i=1}^{44}\frac{d}{da_1}\left(\left(y_i - 100 - a_1t_i\right)^2 \right)\right) &\text{(sum rule)}\\
&= -\frac{1}{2} \left(\sum_{i=1}^{44}\left(2\left(y_i-100-a_it_i\right)\frac{d}{da_1}\left(y_i-100-t_ia_1\right)\right)\right) &\text{(chain rule)}\\
&= -\frac{1}{2} \left(\sum_{i=1}^{44}\left(2(y_i - 100 - a_1t_i)(-t_i) \right)\right) &\text{(simplify)}\\
&= -\frac{1}{2} \left(\sum_{i=1}^{44}\left(-2t_i(y_i - 100 - a_1t_i)\right)\right) &\text{(simplify)}\\
&= -\frac{1}{2} \left(\sum_{i=1}^{44}\left(-2t_iy_i+200t_i+2a_1t_i^2\right)\right) &\text{(distribute)}\\
&= \left(\sum_{i=1}^{44}\left(t_iy_i-100t_i-a_1t_i^2\right)\right) &\text{(divide)}\\
&= \left(\sum_{i=1}^{44}\left(t_iy_i-100t_i\right)\right)-\left(\sum_{i=1}^{44}\left(a_1t_i^2\right)\right) &\text{(sum properties)}\\
&= \left(\sum_{i=1}^{44}\left(t_i\left(y_i-100\right)\right)\right)-\left(\sum_{i=1}^{44}\left(a_1t_i^2\right)\right) &\text{(factor out }t_i)\\
&= \left(\sum_{i=1}^{44} t_i(y_i-100)\right) - \left(\sum_{i=1}^{44} t_i^2\right) a_1&\text{(simplify)}\\
\end{align*}
$$
thus, $\frac{d\ell_1}{da_1} = \left(\sum_{i=1}^{44} t_i(y_i-100)\right) - \left(\sum_{i=1}^{44} t_i^2\right) a_1$

Next is to calculate the second derivative of $\ell_1(a_1;\overrightarrow{t}, \overrightarrow{y})$.

$\frac{d^2}{da_1}\ell_1(a_1^2;\overrightarrow{t_i}, \overrightarrow{y_i})=$

$$
\begin{align*}
\mathscr{} 
&= \frac{d}{da_1}\left(\left(\sum_{i=1}^{44} (t_iy_i-100t_i)\right) - \left(\sum_{i=1}^{44} (a_1t_i^2)\right) \right)&\text{(definition)}\\
&= \frac{d}{da_1}\left(\sum_{i=1}^{44} (t_iy_i-100t_i)\right) - \frac{d}{da_1}\left(\sum_{i=1}^{44} (a_1t_i^2)\right)&\text{(sum of derivatives)}\\
&= -\frac{d}{da_1}\left(\sum_{i=1}^{44} (a_1t_i^2)\right)&\text{(constant rule)}\\
&= - \sum_{i=1}^{44}\frac{d}{da_1}(a_1t_i^2) &\text{(sum of derivatives)}\\
&= -\sum_{i=1}^{44} t_i^2&\text{(power rule)}\\
\end{align*}
$$
thus, $\frac{d^2\ell_2}{da_1^2} = -\sum_{i=1}^{44} t_i^2$

<br>


## Function Four

For points $(t_i, y_i)$ where $i = 1,2,3,...,44$, 

* $f_j$ is a model to predict $y_i$ given an $x_i$ where $f_4(t; a_1,a_2) = 100 + a_1t + a_2\ln(0.005t+1)$. 

* $r_j$, is a set of residuals calculated for each point where $r_{ji} = y_i-f(x_i)$. This means that the following is true: $r_{4i} = y_i -(100 + a_1t_i + a_2\ln(0.005t_i+1)) \Leftrightarrow r_{4i} = y_i -100 - a_1t_i - a_2\ln(0.005t_i+1)\\$

* $p_j$ will be used to denote a probability model of a single residual, $r_{ji}$, where $p_4(t_i, y_i;a_1,a_2) = \frac{1}{\sqrt{2\pi}}e^{-\frac{1}{2}\left(y_i -100 - a_1t_i - a_2\ln(0.005t_i+1)\right)^2}$. 

* $J_j$ will be used to calculate the joint probability of every residual $r_{ji}$, where $J_4(\overrightarrow{t}, \overrightarrow{y}; a_1, a_2) = \prod_{i=1}^{44}\left(\frac{1}{\sqrt{2\pi}}e^{-\frac{1}{2}\left(y_i -100 - a_1t_i - a_2\ln(0.005t_i+1)\right)^2}\right)$.

* $L_j$ will be used to calculate the likelihood of the model $f_2$ given the residuals calculated using the points $(t_i,y_i)$ where $L_4(a_1, a_2;\overrightarrow{t}, \overrightarrow{y}) = \prod_{i=1}^{44}\left(\frac{1}{\sqrt{2\pi}}e^{-\frac{1}{2}\left(y_i -100 - a_1t_i - a_2\ln(0.005t_i+1)\right)^2}\right)$.

* $\ell_j$ will be used to calculate the log-likelihood function from $L$ where 
$\ell_4(a_1, a_2;\overrightarrow{t}, \overrightarrow{y})\\$

$$
\begin{align*}
&= \ln(L_4(a_1,a_2;\textbf{t},\textbf{y})) &\text{(definition)}\\
&= \ln\left(\prod_{i=1}^{44}\frac{1}{\sqrt{2\pi}}e^{-\left(y_i -100 - a_1t_i - a_2\ln(0.005t_i+1)\right)^2/2}\right) &\text{(substitution)}\\
&= \sum_{i=1}^{44}\ln\left(\frac{1}{\sqrt{2\pi}}e^{-\left(y_i -100 - a_1t_i - a_2\ln(0.005t_i+1)\right)^2/2}\right)  &\text{(log product/sum rule)}\\
&= \sum_{i=1}^{44}\left(\ln\left(\frac{1}{\sqrt{2\pi}}\right)+\ln\left(e^{-\left(y_i -100 - a_1t_i - a_2\ln(0.005t_i+1)\right)^2/2}\right)\right)&\text{(another product to sum)}\\
&= \sum_{i=1}^{44}\ln\left(\frac{1}{\sqrt{2\pi}}\right)+\sum_{i=1}^{44}\ln\left(e^{-\left(y_i -100 - a_1t_i - a_2\ln(0.005t_i+1)\right)^2/2}\right)&\text{(separate the sum)}\\
&= \ln\left(\frac{1}{\sqrt{2\pi}}\right)\sum_{i=1}^{44}1+\sum_{i=1}^{44}\ln\left(e^{-\left(y_i -100 - a_1t_i - a_2\ln(0.005t_i+1)\right)^2/2}\right)&\text{(pull out constant)}\\
&= \ln\left(\frac{1}{\sqrt{2\pi}}\right)\sum_{i=1}^{44}1+\sum_{i=1}^{44}-\frac{1}{2}\left(y_i -100 - a_1t_i - a_2\ln(0.005t_i+1)\right)^2\ln\left(e\right)&\text{(bring power down)}\\
&= 44\ln\left(\frac{1}{\sqrt{2\pi}}\right)-\frac{1}{2}\sum_{i=1}^{44}\left(y_i -100 - a_1t_i - a_2\ln(0.005t_i+1)\right)^2&\text{(simplify)}
\end{align*}
$$
thus, $\ell_4(a_1,a_2;\overrightarrow{t}, \overrightarrow{y}) = 44\ln\left(\frac{1}{\sqrt{2\pi}}\right)-\frac{1}{2}\sum_{i=1}^{44}\left(y_i -100 - a_1t_i - a_2\ln(0.005t_i+1)\right)^2$
<br>

### Finding derivatives in respect to $a_1$

First is to calculate the partial derivatives of $\ell_4(a_1, a_2;\overrightarrow{t}, \overrightarrow{y})$ in respect to $a_1$.

$\frac{\partial}{\partial a_1}\ell_4(a_1, a_2;\overrightarrow{t}, \overrightarrow{y})=$

$$
\begin{align*}
\mathscr{} 
&= \frac{\partial}{\partial a_1}\left(44\ln\left(\frac{1}{\sqrt{2\pi}}\right)-\frac{1}{2}\sum_{i=1}^{44}\left(y_i -100 - a_1t_i - a_2\ln(0.005t_i+1)\right)^2\right)&\text{(definition)}\\
&= \frac{\partial}{\partial a_1}\left(44\ln\left(\frac{1}{\sqrt{2\pi}}\right)\right)-\frac{\partial}{\partial a_1}\left(-\frac{1}{2}\sum_{i=1}^{44}\left(y_i -100 - a_1t_i - a_2\ln(0.005t_i+1)\right)^2\right)&\text{(sum of derivatives)}\\
&= -\frac{\partial}{\partial a_1}\left(-\frac{1}{2}\sum_{i=1}^{44}\left(y_i -100 - a_1t_i - a_2\ln(0.005t_i+1)\right)^2\right)&\text{(constant rule)}\\
&= -\frac{1}{2}\sum_{i=1}^{44}\left(\frac{\partial}{\partial a_1}-\left(y_i -100 - a_1t_i - a_2\ln(0.005t_i+1)\right)^2\right)&\text{(constant rule)}\\
&= -\frac{1}{2}\sum_{i=1}^{44}\left(2(y_i -100 - a_1t_i - a_2\ln(0.005t_i+1))\left(-t_i\right)\right)&\text{(chain rule)}\\
&= -\frac{1}{2}\sum_{i=1}^{44}\left(-2t_i(y_i -100 - a_1t_i - a_2\ln(0.005t_i+1))\right)&\text{(simplify)}\\
&= \sum_{i=1}^{44}\left((-\frac{1}{2})(-2t_i)(y_i -100 - a_1t_i - a_2\ln(0.005t_i+1))\right)&\text{(simplify)}\\
&= \sum_{i=1}^{44}\left((t_i)(y_i -100 - a_1t_i - a_2\ln(0.005t_i+1)\right)&\text{(simplify)}\\
&= \sum_{i=1}^{44}\left(t_iy_i -100t_i - t_i^2a_1 - a_2t_i\ln(0.005t_i+1)\right)&\text{(distribute)}\\
&= \left(\sum_{i=1}^{44}(t_iy_i -100t_i)\right) + \left(\sum_{i=1}^{44}(- t_i^2a_1)\right) + \left(\sum_{i=1}^{44}( - a_2t_i\ln(0.005t_i+1))\right)&\text{(sum properties)}\\
&= \left(\sum_{i=1}^{44}t_i(y_i -100)\right) + \left(\sum_{i=1}^{44}(-1)(t_i^2)(a_1)\right) + \left(\sum_{i=1}^{44}(-1)(a_2)(t_i\ln(0.005t_i+1))\right)&\text{(factor out)}\\
&= \left(\sum_{i=1}^{44} t_i(y_i-100)\right) - \left(\sum_{i=1}^{44} t_i^2\right) a_1 - \left(\sum_{i=1}^{44} t_i\ln(0.005t_i + 1)\right) a_2&\text{(rewrite)}
\end{align*}
$$
thus, $\frac{\partial \ell_4}{\partial a_1} =  \left(\sum_{i=1}^{44} t_i(y_i-100)\right) - \left(\sum_{i=1}^{44} t_i^2\right) a_1 - \left(\sum_{i=1}^{44} t_i\ln(0.005t_i + 1)\right) a_2$


Next is to calculate the second derivative of $\ell_4(a_1, a_2;\overrightarrow{t}, \overrightarrow{y})$.

$\frac{\partial^2}{\partial a_1^2}\ell_4(a_1, a_2;\overrightarrow{t}, \overrightarrow{y})=$

$$
\begin{align*}
\mathscr{} 
&= \frac{\partial }{\partial a_1}\left(\left(\sum_{i=1}^{44} t_i(y_i-100)\right) - \left(\sum_{i=1}^{44} t_i^2\right) a_1 - \left(\sum_{i=1}^{44} t_i\ln(0.005t_i + 1)\right) a_2\right)&\text{(definition)}\\
&= \left(\frac{\partial }{\partial a_1}\left(\sum_{i=1}^{44} t_i(y_i-100)\right) - \frac{\partial }{\partial a_1}\left(\sum_{i=1}^{44} t_i^2\right) a_1 - \frac{\partial }{\partial a_1}\left(\sum_{i=1}^{44} t_i\ln(0.005t_i + 1)\right) a_2\right)&\text{(sum of Ds)}\\
&= \left(- \frac{\partial }{\partial a_1}\left(\sum_{i=1}^{44} t_i^2\right) a_1 \right)&\text{(D of constants)}\\
&= -\sum_{i=1}^{44} t_i^2&\text{(constant rule)}
\end{align*}
$$
thus, $\frac{\partial^2\ell_4}{\partial a_1^2} = -\sum_{i=1}^{44} t_i^2$

### Finding derivatives in respect to $a_2$

First is to calculate the partial derivative of $\ell_4(a_1, a_2;\overrightarrow{t}, \overrightarrow{y})$ in respect to $a_2$.

$\frac{\partial}{\partial a_1}\ell_4(a_1, a_2;\overrightarrow{t}, \overrightarrow{y})=$

$$
\begin{align*}
\mathscr{} 
&= \frac{\partial}{\partial a_2}\left(44\ln\left(\frac{1}{\sqrt{2\pi}}\right)-\frac{1}{2}\sum_{i=1}^{44}\left(y_i -100 - a_1t_i - a_2\ln(0.005t_i+1)\right)^2\right)&\text{(definition)}\\
&= \frac{\partial}{\partial a_2}\left(44\ln\left(\frac{1}{\sqrt{2\pi}}\right)\right)-\frac{\partial}{\partial a_2}\left(\frac{1}{2}\sum_{i=1}^{44}\left(y_i -100 - a_1t_i - a_2\ln(0.005t_i+1)\right)^2\right)&\text{(sum of derivatives)}\\
&= -\frac{\partial}{\partial a_2}\left(\frac{1}{2}\sum_{i=1}^{44}\left(y_i -100 - a_1t_i - a_2\ln(0.005t_i+1)\right)^2\right)&\text{(constant rule)}\\
&= -\frac{1}{2}\sum_{i=1}^{44}\left(\frac{\partial}{\partial a_2}\left(y_i -100 - a_1t_i - a_2\ln(0.005t_i+1)\right)^2\right)&\text{(constant rule)}\\
&= -\frac{1}{2}\sum_{i=1}^{44}\left((2)(y_i -100 - a_1t_i - a_2\ln(0.005t_i+1))\left(-\ln(0.005t_i+1)\right)\right)&\text{(chain rule)}\\
&= \sum_{i=1}^{44}\left(-\frac{1}{2}\times 2(y_i -100 - a_1t_i - a_2\ln(0.005t_i+1))\left(-\ln(0.005t_i+1)\right)\right)&\text{(constant)}\\
&= \sum_{i=1}^{44}\left(-1(y_i -100 - a_1t_i - a_2\ln(0.005t_i+1))\left(-\ln(0.005t_i+1)\right)\right)&\text{(simplify)}\\
&= \sum_{i=1}^{44}\left((y_i -100 - a_1t_i - a_2\ln(0.005t_i+1))\left(\ln(0.005t_i+1)\right)\right)&\text{(multiply)}\\
&= \sum_{i=1}^{44}\left((y_i -100)-(a_1t_i )-(a_2\ln(0.005t_i+1))\left(\ln(0.005t_i+1)\right)\right)&\text{(separate)}\\
&= \sum_{i=1}^{44}\left((\left(\ln(0.005t_i+1)\right)y_i -100)-(\left(\ln(0.005t_i+1)\right)a_1t_i )-(\left(\ln(0.005t_i+1)\right)a_2\ln(0.005t_i+1))\right)&\text{(distribute)}\\
&= \sum_{i=1}^{44}\left(\ln(0.005t_i+1)\right)y_i -100)-\sum_{i=1}^{44}(\left(\ln(0.005t_i+1)\right)a_1t_i )-\sum_{i=1}^{44}(\left(\ln(0.005t_i+1)\right)a_2\ln(0.005t_i+1)&\text{(distribute)}\\
&= \sum_{i=1}^{44}\left(\ln(0.005t_i+1)\right)y_i -100)-\sum_{i=1}^{44}(\left(\ln(0.005t_i+1)\right)t_ia_1 )-\sum_{i=1}^{44}\ln(0.005t_i+1)^2a_2&\text{(distribute)}\\
&=\left(\sum_{i=1}^{44} \ln(0.005t_i + 1)(y_i-100)\right) - \left(\sum_{i=1}^{44} t_i\ln(0.005t_i + 1)\right) a_1 - \left(\sum_{i=1}^{44} (\ln(0.005t_i + 1))^2\right) a_2&\text{(rewrite)}
\end{align*}
$$
thus, $\frac{\partial \ell_4}{\partial a_2} = \left(\sum_{i=1}^{44} \ln(0.005t_i + 1)(y_i-100)\right) - \left(\sum_{i=1}^{44} t_i\ln(0.005t_i + 1)\right) a_1 - \left(\sum_{i=1}^{44} (\ln(0.005t_i + 1))^2\right)a_2$

Next is to calculate the second derivative of $\ell_4(a_1, a_2;\overrightarrow{t}, \overrightarrow{y})$.

$\frac{\partial ^2}{\partial a_2^2}\ell_4(a_1;\overrightarrow{t}, \overrightarrow{y})=$

$$
\begin{align*}
\mathscr{} 
&=\frac{\partial}{\partial a_2}\left(\left(\sum_{i=1}^{44} \ln(0.005t_i + 1)(y_i-100)\right) - \left(\sum_{i=1}^{44} t_i\ln(0.005t_i + 1)\right) a_1 - \left(\sum_{i=1}^{44} (\ln(0.005t_i + 1))^2\right) a_2\right)&\text{(definition)}\\
&=\frac{\partial}{\partial a_2}\left(\sum_{i=1}^{44} \ln(0.005t_i + 1)(y_i-100)\right) - \frac{\partial}{\partial a_2}\left(\sum_{i=1}^{44} t_i\ln(0.005t_i + 1)\right) a_1 - \frac{\partial}{\partial a_2}\left(\sum_{i=1}^{44} (\ln(0.005t_i + 1))^2\right) a_2&\text{(D rule)}\\
&=- \frac{\partial}{\partial a_2}\left(\sum_{i=1}^{44} (\ln(0.005t_i + 1))^2\right) a_2&\text{(D of constant)}\\
&=- \left(\sum_{i=1}^{44} \frac{\partial}{\partial a_2}(\ln(0.005t_i + 1))^2a_2\right)&\text{(sum rules)}\\
&= -\sum_{i=1}^{44} (\ln(0.005t_i + 1))^2&\text{(rewrite)}\\
\end{align*}
$$
thus, $\frac{\partial ^2\ell_4}{\partial a_2^2} = -\sum_{i=1}^{44} (\ln(0.005t_i + 1))^2$

Next is to calculate $\frac{\partial^2\ell_4}{\partial a_1a_2}$.

$\frac{\partial ^2}{\partial a_1a_2}\ell_4(a_1, a_2;\overrightarrow{t}, \overrightarrow{y})=$

$$
\begin{align*}
\mathscr{} 
&=\frac{\partial}{\partial a_2}\left(\left(\sum_{i=1}^{44} \ln(0.005t_i + 1)(y_i-100)\right) - \left(\sum_{i=1}^{44} t_i\ln(0.005t_i + 1)\right) a_1 - \left(\sum_{i=1}^{44} (\ln(0.005t_i + 1))^2\right)\right) a_2&\text{(definition)}\\
&=\frac{\partial}{\partial a_2}\left(\sum_{i=1}^{44} \ln(0.005t_i + 1)(y_i-100)\right) - \frac{\partial}{\partial a_2}\left(\sum_{i=1}^{44} t_i\ln(0.005t_i + 1)\right) a_1 - \frac{\partial}{\partial a_2}\left(\sum_{i=1}^{44} (\ln(0.005t_i + 1))^2\right) a_2&\text{(D rule)}\\
&=- \frac{\partial}{\partial a_2}\left(\sum_{i=1}^{44} (\ln(0.005t_i + 1))^2\right) a_2&\text{(D of constant)}\\
&=- \left(\sum_{i=1}^{44} \frac{\partial}{\partial a_2}(\ln(0.005t_i + 1))^2a_2\right)&\text{(sum rules)}\\
&= -\sum_{i=1}^{44} (\ln(0.005t_i + 1))^2&\text{(rewrite)}\\
\end{align*}
$$
thus, $\frac{\partial ^2\ell_4}{\partial a_2^2} = -\sum_{i=1}^{44} (\ln(0.005t_i + 1))^2$

Finally, we will be calculating $\frac{\partial ^2\ell_4}{\partial a_2a_1}$

$\frac{\partial \ell_4}{\partial a_2a_1}$
$$
\begin{align*}
\mathscr{}
&=\frac{\partial}{\partial a_1}\left(\left(\sum_{i=1}^{44} \ln(0.005t_i + 1)(y_i-100)\right) - \left(\sum_{i=1}^{44} t_i\ln(0.005t_i + 1)\right) a_1 - \left(\sum_{i=1}^{44} (\ln(0.005t_i + 1))^2\right)\right) &\text{definition}\\
&=\frac{\partial}{\partial a_1}\left(\sum_{i=1}^{44} \ln(0.005t_i + 1)(y_i-100)\right) - \frac{\partial}{\partial a_1}\left(\sum_{i=1}^{44} t_i\ln(0.005t_i + 1)\right) a_1 - \frac{\partial}{\partial a_1}\left(\sum_{i=1}^{44} (\ln(0.005t_i + 1))^2\right) &\text{summation rule}\\
&=- \frac{\partial}{\partial a_1}\left(\sum_{i=1}^{44} t_i\ln(0.005t_i + 1)\right) a_1  &\text{D of constant}\\
&=- \sum_{i=1}^{44} t_i\ln(0.005t_i + 1) &\text{power rule}\\
\end{align*}
$$
Thus, $\frac{\partial ^2\ell_4}{\partial a_2a_1} =- \sum_{i=1}^{44} t_i\ln(0.005t_i + 1)$

## Function Five

For points $(t_i, y_i)$ where $i = 1,2,3,...,44$, 

* $f_j$ is a model to predict $y_i$ given an $x_i$ where $f_5(t; a_1) = 100e^{-0.00005t} + a_1te^{-0.00005t}$. 

* $r_j$, is a set of residuals calculated for each point where $r_{ji} = y_i-f(x_i)$. This means that the following is true: $r_{5i} = y_i -(100e^{-0.00005t_i} + a_1t_ie^{-0.00005t_i}) \Leftrightarrow r_{5i} = y_i -100e^{-0.00005t_i} - a_1t_ie^{-0.00005t_i}\\$


* $p_j$ will be used to denote a probability model of a single residual, $r_{ji}$, where $p_5(t_i, y_i;a_1) = \frac{1}{\sqrt{2\pi}}e^{-\frac{1}{2}\left(y_i -100e^{-0.00005t_i} - a_1t_ie^{-0.00005t_i}\right)^2}$. 

* $J_j$ will be used to calculate the joint probability of every residual $r_{ji}$, where $J_5(\overrightarrow{t}, \overrightarrow{y}; a_1) = \prod_{i=1}^{44}\left(\frac{1}{\sqrt{2\pi}}e^{-\frac{1}{2}\left(y_i -100e^{-0.00005t_i} - a_1t_ie^{-0.00005t_i}\right)^2}\right)$.

* $L_j$ will be used to calculate the likelihood of the model $f_2$ given the residuals calculated using the points $(t_i,y_i)$ where $L_5(a_1;\overrightarrow{t}, \overrightarrow{y}) = \prod_{i=1}^{44}\left(\frac{1}{\sqrt{2\pi}}e^{-\frac{1}{2}\left(y_i -100e^{-0.00005t_i} - a_1t_ie^{-0.00005t_i}\right)^2}\right)$.

* $\ell_j$ will be used to calculate the log-likelihood function from $L$ where 
$\ell_5(a_1;\overrightarrow{t}, \overrightarrow{y})\\$

$$
\begin{align*}
&= \ln(L_5(a_1;\textbf{t},\textbf{y})) &\text{(definition)}\\
&= \ln\left(\prod_{i=1}^{44}\frac{1}{\sqrt{2\pi}}e^{-\left(y_i -100e^{-0.00005t_i} - a_1t_ie^{-0.00005t_i}\right)^2/2}\right) &\text{(substitution)}\\
&= \sum_{i=1}^{44}\ln\left(\frac{1}{\sqrt{2\pi}}e^{-\left(y_i -100e^{-0.00005t_i} - a_1t_ie^{-0.00005t_i}\right)^2/2}\right)  &\text{(log product/sum rule)}\\
&= \sum_{i=1}^{44}\left(\ln\left(\frac{1}{\sqrt{2\pi}}\right)+\ln\left(e^{-\left(y_i -100e^{-0.00005t_i} - a_1t_ie^{-0.00005t_i}\right)^2/2}\right)\right)&\text{(another product to sum)}\\
&= \sum_{i=1}^{44}\ln\left(\frac{1}{\sqrt{2\pi}}\right)+\sum_{i=1}^{44}\ln\left(e^{-\left(y_i -100e^{-0.00005t_i} - a_1t_ie^{-0.00005t_i}\right)^2/2}\right)&\text{(separate the sum)}\\
&= \ln\left(\frac{1}{\sqrt{2\pi}}\right)\sum_{i=1}^{44}1+\sum_{i=1}^{44}\ln\left(e^{-\left(y_i -100e^{-0.00005t_i} - a_1t_ie^{-0.00005t_i}\right)^2/2}\right)&\text{(pull out constant)}\\
&= \ln\left(\frac{1}{\sqrt{2\pi}}\right)\sum_{i=1}^{44}1+\sum_{i=1}^{44}-\frac{1}{2}\left(y_i -100e^{-0.00005t_i} - a_1t_ie^{-0.00005t_i}\right)^2\ln\left(e\right)&\text{(bring power down)}\\
&= 44\ln\left(\frac{1}{\sqrt{2\pi}}\right)-\frac{1}{2}\sum_{i=1}^{44}\left(y_i -100e^{-0.00005t_i} - a_1t_ie^{-0.00005t_i}\right)^2&\text{(simplify)}
\end{align*}
$$
thus, $\ell_5(a_1;\overrightarrow{t}, \overrightarrow{y}) = 44\ln\left(\frac{1}{\sqrt{2\pi}}\right)-\frac{1}{2}\sum_{i=1}^{44}\left(y_i -100e^{-0.00005t_i} - a_1t_ie^{-0.00005t_i}\right)^2$

### Finding the derivatives

Next is to calculate the derivative of $\ell_5(a_1;\overrightarrow{t},\overrightarrow{y})$

$\frac{d}{da_1}\ell_5(a_1;\overrightarrow{t}, \overrightarrow{y})=$

$$
\begin{align*}
&= \frac{d}{da_1}\left( 44\ln\left(\frac{1}{\sqrt{2\pi}}\right)-\frac{1}{2}\sum_{i=1}^{44}\left(y_i -100e^{-0.00005t_i} - a_1t_ie^{-0.00005t_i}\right)^2\right)&\text{(definition)}\\
&= \frac{d}{da_1}\left(44\ln\left(\frac{1}{\sqrt{2\pi}}\right)\right)\frac{d}{da_1}\left(-\frac{1}{2}\sum_{i=1}^{44}\left(y_i -100e^{-0.00005t_i} - a_1t_ie^{-0.00005t_i}\right)^2\right)&\text{(sum of D)}\\
&=\frac{d}{da_1}\left(-\frac{1}{2}\sum_{i=1}^{44}\left(y_i -100e^{-0.00005t_i} - a_1t_ie^{-0.00005t_i}\right)^2\right)&\text{(D of constant)}\\
&=-\frac{1}{2}\sum_{i=1}^{44}\left(\frac{d}{da_1}\left(y_i -100e^{-0.00005t_i} - a_1t_ie^{-0.00005t_i}\right)^2\right)&\text{(sum of D)}\\
&=-\frac{1}{2}\sum_{i=1}^{44}\left(2\left(y_i -100e^{-0.00005t_i} - a_1t_ie^{-0.00005t_i}\right)(t_ie^{-0.00005t_i})\right)&\text{(chain rule)}\\
&=-\sum_{i=1}^{44}\left((y_i -100e^{-0.00005t_i} - a_1t_ie^{-0.00005t_i})(t_ie^{-0.00005t_i})\right)&\text{(constant)}\\
&=-\sum_{i=1}^{44}\left((t_ie^{-0.00005t_i})(y_i -100e^{-0.00005t_i}) + (t_ie^{-0.00005t_i})(- a_1t_ie^{-0.00005t_i})\right)&\text{(constant)}\\
&=-\sum_{i=1}^{44}\left((t_ie^{-0.00005t_i})(y_i -100e^{-0.00005t_i}) + (-1) a_1(t_ie^{-0.00005t_i})^2\right)&\text{(constant)}\\
&=\left(-\sum_{i=1}^{44}(t_ie^{-0.00005t_i})(y_i -100e^{-0.00005t_i})\right) + \left(-\sum_{i=1}^{44}(-1) a_1(t_ie^{-0.00005t_i})^2\right)&\text{(summation rule)}\\
&=\left(-\sum_{i=1}^{44}(t_ie^{-0.00005t_i})(y_i -100e^{-0.00005t_i})\right) + \left(\sum_{i=1}^{44} a_1(t_ie^{-0.00005t_i})^2\right)&\text{(constant)}\\
&=-1\left(\sum_{i=1}^{44}(t_ie^{-0.00005t_i})(y_i -100e^{-0.00005t_i})\right) + \left(\sum_{i=1}^{44} a_1(t_ie^{-0.00005t_i})^2\right)&\text{(constant)}\\
&=\left(\sum_{i=1}^{44}(t_ie^{-0.00005t_i})(y_i -100e^{-0.00005t_i})\right) + (-1)\left(\sum_{i=1}^{44} a_1(t_ie^{-0.00005t_i})^2\right)&\text{(rewrite)}\\
&=\left(\sum_{i=1}^{44} t_ie^{-0.00005t_i}(y_i-100e^{-0.00005t_i})\right) - \left(\sum_{i=1}^{44} (t_ie^{-0.00005t_i})^2\right) a_1&\text{(rewrite)}\\
\end{align*}
$$
thus, $\frac{d\ell_5}{da_1} =\left(\sum_{i=1}^{44} t_ie^{-0.00005t_i}(y_i-100e^{-0.00005t_i})\right)-\left(\sum_{i=1}^{44}(t_ie^{-0.00005t_i})^2\right)a_1$

Next is to calculate the second derivative of $\ell_5(a_1;\overrightarrow{t}, \overrightarrow{y})$.

$\frac{d^2}{da_1^2}\ell_5(a_1;\overrightarrow{t_i}, \overrightarrow{y_i})=$

$$
\begin{align*}
\mathscr{} 
&=\frac{d}{da_1}\left(\left(\sum_{i=1}^{44} t_ie^{-0.00005t_i}(y_i-100e^{-0.00005t_i})\right) - \left(\sum_{i=1}^{44} (t_ie^{-0.00005t_i})^2\right) a_1\right)&\text{(definition)}\\
&=\frac{d}{da_1}\left(\sum_{i=1}^{44} t_ie^{-0.00005t_i}(y_i-100e^{-0.00005t_i})\right) - \frac{d}{da_1}\left(\sum_{i=1}^{44} (t_ie^{-0.00005t_i})^2 a_1\right)&\text{(D of sums)}\\
&=- \frac{d}{da_1}\left(\sum_{i=1}^{44} (t_ie^{-0.00005t_i})^2 a_1\right)&\text{(D of constants)}\\
&=- \sum_{i=1}^{44} (t_ie^{-0.00005t_i})^2&\text{(power rule)}\\
\end{align*}
$$

thus, $\frac{d^2\ell_5}{da_1^2} =- \sum_{i=1}^{44} (t_ie^{-0.00005t_i})^2$


<br>
